[package]
publish = false
name    = "minicbor-tests-nostd"
version = "0.1.0"
authors = ["Toralf Wittner <tw@dtex.org>"]
edition = "2018"

[dependencies]
minicbor = { path = "../minicbor" }

[profile.dev]
panic = "abort"

